name: yes_no_app
description: A new Flutter project.
publish_to: 'none ivan'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  provider: ^6.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
